### ISSUE TITLE
How to navigate with Racecar

### ISSUE THREAD

**Issue by NevzatBOL** [mit-racecar/racecar#5]
I want to make real time navigation with racecar. When I run the navigation packages, it sends me the data of type cmd_vel Twist. How can I check the motors using this data?

**Comment by CapitalZe** [comment]
Do you mean the navigation_stack or a navigation package in this repository?

**Comment by NevzatBOL** [comment]
I didn't find navigation package this repository. I created a navigation_stack in this repository. I do not know how to use a transformation to control engines.

**Comment by CapitalZe** [comment]
I'm having a similar issue. I also tried nav2d, before I found the
Formula1Epoch repository on github. I'll be giving that a go tomorrow.
Let me know if you make any progress, i'll be curious to learn how to do it.

Cheers!
[image: 5]

**Comment by xoxota99** [comment]
What is the data in the Twist message that you're getting? Could it just be an error value for steering (and assume constant velocity to the motor)?
