### ISSUE TITLE
How to train the car on new course

### ISSUE THREAD

**Issue by ArtlyStyles** [mit-racecar/racecar#7]
Hi, is there any documents about how to collect training sample and train the car for a new course?

**Comment by ArtlyStyles** [comment]
Can anyone help?

**Comment by xoxota99** [comment]
I would also love to know the answer to this. At a high level, as I understand it, you launch the joystick teleop, capture all lidar data to a rosbag or log file, then use the captured to create a map offline with some MATLAB magic. Repeat that a couple of times to create an "averaged" view of your track, and export to PNG, I guess.

**Comment by mboulet** [comment]
Hi, this repo does not currently contain the "high level" autonomy that you describe. The intent of this repo is to provide a platform with low-level control for others to build such autonomous capability on their own. But it sounds like a great idea - you should try it!
